version: '3.8'
services:
  mysql:
    image: mysql:8.0.19
    restart: always
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=debezium
      - MYSQL_ROOT_PASSWORD=pwd
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-time-zone=+09:00
    volumes:
      - ./init:/docker-entrypoint-initdb.d
